# Generated by Django 4.1.7 on 2023-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientId', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=500)),
                ('redirectUri', models.CharField(max_length=200)),
            ],
        ),
    ]
